<?php
/**
 * Created by Q2A Market.
 * http://www.q2amarket.com
 *
 * Project: lion
 * File: options.php
 * Description:
 */

if ( ! defined('QA_VERSION')) {
    header('Location: /');
    exit;
}

class qa_html_theme_layer extends qa_html_theme_base
{
    var $theme_directory;
    var $theme_url;

    public function __construct($template, $content, $rooturl, $request)
    {
        global $qa_layers;
        $this->theme_directory = $qa_layers[ 'Lion Options' ][ 'directory' ];
        $this->theme_url       = $qa_layers[ 'Lion Options' ][ 'urltoroot' ];

        parent::__construct($template, $content, $rooturl, $request);
    }

    function doctype()
    {
        global $qa_request;

        $this->content[ 'navigation' ][ 'sub' ][ 'lionoptions' ] = [
            'label'    => 'Lion Options',
            'url'      => qa_path_html('admin', ['qa_1' => 'lionoptions']),
            'selected' => FALSE,
        ];

        if ($qa_request == 'admin/lionoptions') {
            $this->content[ 'navigation' ][ 'sub' ][ 'lionoptions' ][ 'selected' ] = TRUE;
            $this->template                                                        = 'lionoptions';
            $this->content[ 'error' ]                                              = '';
            $this->content[ 'suggest_next' ]                                       = '';
            $this->content[ 'title' ]                                              = 'Lion Options';
        }

//        $path = qa_path('admin', ['qa_1' => 'lionoptions']);
//        do_print($path);
        do_print($this->content);

//        $this->content['custom'] = '<h1>Lion Options</h1>';


        parent::doctype(); // TODO: Change the autogenerated stub
    }
}